### ISSUE TITLE
Why not use more conventional terminology?

### ISSUE THREAD

**Issue by MarkR42** [gto76/comp-cpp#4]
It's quite interesting, but why not use more conventional microprocessor terminology?

READ -> LOAD
WRITE -> STORE
IF -> BRANCH
SHIFT RIGHT -> ASR (Arithmetic shift right)

It's also seems a bit limiting that the code and data share the same address space, when there is so little to share. Almost seems to encourage the use of self-modifying code.

**Comment by gto76** [comment]
Thank for suggestions,
tried to make it not too scarry for the layman, so i think at least `if` and `shift right` is better...
I don't think I totaly understand the later part, I just tried to make it as basic as possible.

**Comment by kdbanman** [comment]
> seems a bit limiting that the code and data share the same address space

@MarkR42, you're correct.  It's a 4 bit computer.  It runs at 1 Hz.  Limitation is exactly the game here.  Convention and practicality don't matter.

@gto76, this is a wonderful toy.  You "just tried to make it as basic as possible" and you succeeded.

**Comment by gto76** [comment]
I made the "Mark II" version with separate address space:
https://github.com/gto76/comp-m2

Thanks for the advice!
